// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// preprocess_file
std::vector<std::string> preprocess_file(const std::string& filePath, bool only_meta);
RcppExport SEXP _pxR2_preprocess_file(SEXP filePathSEXP, SEXP only_metaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filePath(filePathSEXP);
    Rcpp::traits::input_parameter< bool >::type only_meta(only_metaSEXP);
    rcpp_result_gen = Rcpp::wrap(preprocess_file(filePath, only_meta));
    return rcpp_result_gen;
END_RCPP
}
// px_parse
List px_parse(const std::string& filePath, bool only_meta, bool debug);
RcppExport SEXP _pxR2_px_parse(SEXP filePathSEXP, SEXP only_metaSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filePath(filePathSEXP);
    Rcpp::traits::input_parameter< bool >::type only_meta(only_metaSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(px_parse(filePath, only_meta, debug));
    return rcpp_result_gen;
END_RCPP
}
// px_parse_meta_string
Rcpp::List px_parse_meta_string(const std::string& line, bool debug);
RcppExport SEXP _pxR2_px_parse_meta_string(SEXP lineSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type line(lineSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(px_parse_meta_string(line, debug));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pxR2_preprocess_file", (DL_FUNC) &_pxR2_preprocess_file, 2},
    {"_pxR2_px_parse", (DL_FUNC) &_pxR2_px_parse, 3},
    {"_pxR2_px_parse_meta_string", (DL_FUNC) &_pxR2_px_parse_meta_string, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_pxR2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
