# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

preprocess_file <- function(filePath, only_meta = FALSE) {
    .Call(`_pxR2_preprocess_file`, filePath, only_meta)
}

#' Parse a px file
#'
#' This function read a px file, parsing data and metadata and warnins if
#' the PX file is malformatted.
#'
#' @param filePath path to PX file ending in .px or .PX
#' @param only_meta Boolean, set to true if you only want to extract the metadata.
#' @param debug Boolean, set to true if you want to debug the parser step-by-step.
#' @return Returns a list of metadata and data.
#' @export
px_parse <- function(filePath, only_meta = FALSE, debug = FALSE) {
    .Call(`_pxR2_px_parse`, filePath, only_meta, debug)
}

#' Parse a single px-formatted string.
#'
#' This function parses a string in px-format and returns an error if the format
#' is malformatted.
#'
#' @param line A string in PX-format with at least a keyword and value.
#' @param debug Boolean, set to true if you want to debug the parser step-by-step.
#' @return Returns a parsed list with four elements: keyword, language, subkeys and values.
#' @export
#' @examples
#' px_parse_meta_string("VALUENOTE[sv](\"Norway\")=\"Break in time series\";")
#' px_parse_meta_string("NOTE=\"Preliminary data\";")
#' px_parse_meta_string("CODEPAGE=\"UTF-8\";")
px_parse_meta_string <- function(line, debug = FALSE) {
    .Call(`_pxR2_px_parse_meta_string`, line, debug)
}

